name: Deploy to RKE2 Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH to known hosts
      run: |
        ssh-keyscan -t rsa 100.127.34.10> >> ~/.ssh/known_hosts

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

    - name: SSH into the VM and apply deployment
      run: |
        ssh -o StrictHostKeyChecking=no admink8s@100.127.34.10> << 'EOF'
          kubectl apply -f /path/to/your/deployment.yaml
        EOF







