name: Deploy to RKE2 Cluster k8s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa 100.127.34.10 >> ~/.ssh/known_hosts || echo "SSH keyscan failed, but continuing"

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

    - name: SSH into the VM and apply deployment
      run: |
        ssh -o StrictHostKeyChecking=no admink8s@100.127.34.10 << 'EOF'
          kubectl apply -f deployment.yaml || echo "Failed to apply deployment.yaml"
        EOF








