name: Kubernetes Debug Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Azure Subscription
        run: az account show
